NAME = philo

CC = cc

CFLAGS = -Wall -Wextra -Werror -g

SRC = 	src/philo.c \
		src/ft_calloc.c

OBJ = $(SRC:.c=.o)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

all: $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
